In [15]:
import numpy as np

In [16]:
arr=np.array([[4,4],[3,4],[3,1]])
print(arr)

[[4 4]
 [3 4]
 [3 1]]


In [18]:
arrw=np.arange(3,19)
print(arrw)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [34]:
rand_6=np.random.randint(1,9,12)
print(rand_6)

[4 6 3 8 1 4 4 5 6 1 8 2]


In [52]:
rand_5=np.random.random((6))
print(rand_5)

[0.92340237 0.76142758 0.29309249 0.28482678 0.25186339 0.85470137]


In [54]:
rand_4=rand_5+4
rand_4

array([4.92340237, 4.76142758, 4.29309249, 4.28482678, 4.25186339,
       4.85470137])

In [64]:


value = np.random.uniform(-2, 2)
print(value)

1.051281781435938


In [65]:
import numpy as np
feature = np.arange(6,21)
print(feature)
label = (3*feature)+4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [66]:
noise = np.random.uniform(-2,2,len(label))
print(noise)
label = label+noise  # write your code here
print(label)

[-1.38583128 -0.48214873  0.32504569 -0.60901863  0.1843016   0.26947726
  0.29232436  0.91717191  1.83743781 -1.6905267  -0.5819994   1.911118
 -0.23470701 -0.82528621 -0.57671363]
[20.61416872 24.51785127 28.32504569 30.39098137 34.1843016  37.26947726
 40.29232436 43.91717191 47.83743781 47.3094733  51.4180006  56.911118
 57.76529299 60.17471379 63.42328637]


In [67]:
noise = np.random.uniform(-2,2,len(label))
print(noise)
label = label+noise  # write your code here
print(label)

[-0.28369753  1.30508456  0.19483441 -0.77394675  1.79411271  0.14240219
  1.90987926 -0.47362598 -1.8668763   1.04816594  0.56581109  1.8719255
  0.74116355 -0.62517401 -1.36893627]
[20.33047119 25.82293583 28.5198801  29.61703462 35.97841431 37.41187945
 42.20220362 43.44354593 45.97056151 48.35763924 51.98381169 58.78304349
 58.50645654 59.54953978 62.0543501 ]
